### ISSUE TITLE
关于反向代理

### ISSUE THREAD

**Issue by shmilyty** [nonebot/adapter-telegram#12]
![image](https://user-images.githubusercontent.com/61276699/187359630-7d9bae14-506c-4e2e-8e50-c8b1b5124934.png)
我是把bot搭建在云服务器上的，前面的步骤都做完了，现在到这一步，有三个不理解的问题：
- 这一段文本应该填在哪里（是不是env.dev）
- 这一段文本中的`tg.yourdomain.com`是否需要替换，应该替换成什么？
- 这一段文本中的`http://127.0.0.1:4000`是否应该替换成服务器地址:4000？

**Comment by j1g5awi** [comment]
1. 这一段是在有公网 IP 的服务器上 nginx 的配置文件。我的服务器上该文件位置为： `/etc/nginx/conf.d/frp.conf`。
2. tg.yourdomain.com 替换成你自己要解析到的该服务器的域名。
3. 这是在服务器上的反向代理，不需要更改。

如果你不知道这些反代是为了什么，建议[使用 Long polling 获取更新](https://github.com/nonebot/adapter-telegram/blob/beta/MANUAL.md#%E4%BD%BF%E7%94%A8-long-polling-%E8%8E%B7%E5%8F%96%E6%9B%B4%E6%96%B0%E6%8E%A8%E8%8D%90)。

**Comment by shmilyty** [comment]
好的，谢谢您，我没有注意到可以直接用 Long polling。

还想问一个关于代理的问题。

我目前用的是[hax.co.id](https://hax.co.id/)的公共代理，测试可用，但是代理的形式是地址+端口+secret的形式，那么telegram_proxy应该怎么填？
![image](https://user-images.githubusercontent.com/61276699/187430727-0c79f813-fb6f-4748-abcd-eb50ce33a85b.png)

**Comment by j1g5awi** [comment]
该代理使用的是 MTProto 协议，NoneBot 无法使用。
