### ISSUE TITLE
关于机器人无法应答

### ISSUE THREAD

**Issue by shmilyty** [nonebot/adapter-telegram#13]
google了一下，没有找到什么免费的tg代理~~不太擅长找资源~~因此在服务器上挂了一个梯子（clashshell）。
![image](https://user-images.githubusercontent.com/61276699/187575853-05879cf0-b05e-4cec-8464-f733fc5b6b29.png)
然后我根据文档，按照默认配置新建了一个 Nonebot，安装了`httpx`和`adapter-telegram`，填了一下配置文件:
![image](https://user-images.githubusercontent.com/61276699/187576368-1541ac76-007c-4462-a859-3887eee19429.png)
![image](https://user-images.githubusercontent.com/61276699/187576405-11eb6825-57d1-4e59-a6bf-0b66e54fd37f.png)
![image](https://user-images.githubusercontent.com/61276699/187576429-280cbfeb-6b53-4b62-afd5-8b2f9ea44b58.png)
接下来，我运行了Nonebot~~没有报错~~
![image](https://user-images.githubusercontent.com/61276699/187576546-0a2b10d3-7835-45cf-9390-551cdfea73e1.png)
但是tg端的命令没有任何响应，nb端也没有反应
![image](https://user-images.githubusercontent.com/61276699/187576605-fe036fc0-1b3b-458d-89e7-6df32245d707.png)
我怀疑我哪个步骤漏掉了:(

**Comment by j1g5awi** [comment]
.env 里需要配置 telegram_proxy，你开了代理却没让 NoneBot 调用。

Telegram 适配器在 Polling 模式下成功启动，log 里会有一行 `Start poll`。

**Comment by shmilyty** [comment]
我搞了一下，已经把telegram_proxy填上去了，填的链接看上去是有效的。
![image](https://user-images.githubusercontent.com/61276699/187852188-20f0252a-95e0-4c6e-b862-2f5977dadcc8.png)
但是我用`nb run`运行，还是没有出现Start poll。
![image](https://user-images.githubusercontent.com/61276699/187851681-a8c89ff0-e554-41d5-a10d-e44640034226.png)
请问这个Polling模式是需要手动打开的吗？

**Comment by j1g5awi** [comment]
默认就是 Polling 模式。

我上面把 `telegram` 打成 `telegrem`，你貌似也打错了。

**Comment by shmilyty** [comment]
我又改了一下，但是没什么大用，然后我重新装了一遍nb，还是没有什么用。
![image](https://user-images.githubusercontent.com/61276699/188141511-1fd35487-09da-463d-bf59-e4af103a5984.png)
![image](https://user-images.githubusercontent.com/61276699/188141635-aca454e6-91f7-461a-8e5c-a3df9504928c.png)

**Comment by j1g5awi** [comment]
建议再检查下代理是否可用，比如 `curl google.com --proxy 代理地址`

**Comment by shmilyty** [comment]
![image](https://user-images.githubusercontent.com/61276699/188251718-ff2edb80-07c0-458f-8c7d-76d867bcfa12.png)
我代理地址填的是`服务器地址:9999`，不知道对不对（好像shellclash默认端口就是9999）
看了一下shellclash的设置，好像有些端口没有设置。
![image](https://user-images.githubusercontent.com/61276699/188251767-aad8fe2f-cecb-4ea8-9712-13b2de7298bc.png)
请问这个代理的端口应该填哪个😭？

**Comment by mrchenxxx** [comment]
破案了，你的telegram_proxy是你本地的地址，比如说你的梯子代理端口是7890，则要设置成telegram_proxy = "http://127.0.0.1:7890"
具体端口号是多少你要看你的梯子，比如我用的clash，它的端口是7890你就要设置成7890
![端口](https://user-images.githubusercontent.com/44868578/189482675-5e3b8059-6acf-463b-9841-adf0a1167546.png)

**Comment by shmilyty** [comment]
呜呜，你说的对，我前段时间就发现了，现在貌似的问题是在服务器配置shellclash curl不通，可能是我哪里有点问题，我再自己研究一下，如果你有这方面的经验能分享一下吗？

还有我最近刚刚开学，事情有点多，可能无法及时回复或者去跟进你们的指导，深表歉意。

**Comment by mrchenxxx** [comment]
你按照我说的做就行，就能够ping通了。。 不行的话再微我

**Comment by shmilyty** [comment]
我刚刚试了一下，好像还是无法运行
![image](https://user-images.githubusercontent.com/61276699/189487889-63bf9245-a2b1-4357-aa41-dd3e80e45957.png)
主要问题是代理用不了
![image](https://user-images.githubusercontent.com/61276699/189487922-50938214-847e-45e3-a4df-9076dd7ecb8c.png)
我检查了一下，我设置的端口就是7890
![image](https://user-images.githubusercontent.com/61276699/189487946-e3da3201-339d-4a9c-a475-7fc5ecc74a3f.png)

**Comment by mrchenxxx** [comment]
把系统代理去掉试试







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月10日(星期六) 晚上10:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nonebot/adapter-telegram] 关于机器人无法应答 (Issue #13)





 
我刚刚试了一下，好像还是无法运行
 
 主要问题是代理用不了
 
 我检查了一下，我设置的端口就是7890

**Comment by shmilyty** [comment]
您的意思是把 --poxy 127...删掉吗？

好像还是不行
![image](https://user-images.githubusercontent.com/61276699/189488198-b224891a-fee2-4139-9e70-382f83735f8c.png)

**Comment by mrchenxxx** [comment]
明天我远程看看？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月10日(星期六) 晚上10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nonebot/adapter-telegram] 关于机器人无法应答 (Issue #13)





 
您的意思是把 --poxy 127...删掉吗？
 
好像还是不行

**Comment by shmilyty** [comment]
好的，谢谢您，早点睡

**Comment by mrchenxxx** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月10日(星期六) 晚上10:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nonebot/adapter-telegram] 关于机器人无法应答 (Issue #13)





 
好的，谢谢您，早点睡

**Comment by shacha086** [comment]
要不看看代理在其他设备上是否工作

**Comment by j1g5awi** [comment]
因长时间无回复关闭此 Issue，如有问题可自行再打开。
