### ISSUE TITLE
卡在start poll，发消息也没有任何反应

### ISSUE THREAD

**Issue by iven13465** [nonebot/adapter-telegram#14]
![image](https://user-images.githubusercontent.com/95957360/188296872-bf739c53-07d4-4631-a99d-b75aaa113e62.png)
配置项
![image](https://user-images.githubusercontent.com/95957360/188296914-eefc7804-e5f4-4c48-8282-2d1985bd0db5.png)

![image](https://user-images.githubusercontent.com/95957360/188296976-6d7cbcb7-15a5-4063-9495-43f555374f81.png)
我的服务器在国外，所以并没有配置代理

**Comment by j1g5awi** [comment]
出現「Start poll」表示網絡環境正常，解析消息時錯誤應該會報錯，這種靜默狀態還真是奇怪。

你可能需要自行 Debug 以提供更多信息，我無法復現此情況。

**Comment by iven13465** [comment]
> 出現「Start poll」表示網絡環境正常，解析消息時錯誤應該會報錯，這種靜默狀態還真是奇怪。
> 
> 你可能需要自行 Debug 以提供更多信息，我無法復現此情況。

是我的问题，我是直接在saved messages里发的（）
