### ISSUE TITLE
如何回复别人发送的消息

### ISSUE THREAD

**Issue by mrchenxxx** [nonebot/adapter-telegram#15]
![reply](https://user-images.githubusercontent.com/44868578/189485340-1cb3de49-26fb-41f8-965f-de6ee4b6215d.png)

**Comment by j1g5awi** [comment]
你可以在調用任何發送消息的 API 時使用可選參數 `reply_to_message_id` 來指定要回覆的消息，message_id 可以通過 `event.message_id` 獲取。

示例：

```python
@on_command("reply").handle()
async def _(bot: Bot, event: MessageEvent):
    with open("./docs/logo.png", "rb") as f:
        await bot.send(
            event,
            File.photo(f.read()),
            reply_to_message_id=event.message_id
        )
```

**Comment by mrchenxxx** [comment]
谢谢您，成功了

**Comment by mrchenxxx** [comment]
谢谢您，成功了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月11日(星期天) 下午3:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nonebot/adapter-telegram] 问一下怎么回复别人发送的消息具体看一下图片 (Issue #15)





 
你可以在調用任何發送消息的 API 時使用可選參數 reply_to_message_id 來指定要回覆的消息，message_id 可以通過 event.message_id 獲取。
 
示例：
 @on_command("reply").handle() async def _(bot: Bot, event: MessageEvent):     with open("./docs/logo.png", "rb") as f:         await bot.send(             event,             File.photo(f.read()),             reply_to_message_id=event.message_id         )
