### ISSUE TITLE
关于启动失败问题 You must pass the application as an import string to enable 'reload' or 'workers'.

### ISSUE THREAD

**Issue by MaGua-Bishop** [nonebot/adapter-telegram#17]
很抱歉打扰到您，但是我在启动出现了一个报错，我Google百度后实在无法解决
如图并没有出现error类型日志
![image](https://user-images.githubusercontent.com/75660993/190945067-edbd368a-1e13-4212-abe0-c69e3cd87991.png)
但是退出的code为1，我怀疑是 
`09-19 11:21:39 [WARNING] uvicorn | You must pass the application as an import string to enable 'reload' or 'workers'.`
引发的问题，但是我在查询nonebot的issue没有人出现和我一样的问题，并且我观察到fastapi_reload已经为True了。我不知道该怎么解决
![image](https://user-images.githubusercontent.com/75660993/190945221-1a0093a3-177e-4bfd-ae70-06b53e6f0e68.png)

我当前网络能够直接访问telegram，所以将代理设置注释了

![image](https://user-images.githubusercontent.com/75660993/190945421-cde0f7e3-bb0d-4ddc-a2f8-11ef2d02a93b.png)

![image](https://user-images.githubusercontent.com/75660993/190945458-3e794d7c-daa2-428d-901a-d6b519ceaf06.png)

nonebot 版本貌似也没有什么问题

希望能得到指点，跪谢

**Comment by j1g5awi** [comment]
bot.py 里需要有：

```
app = nonebot.get_asgi()
nonebot.run(app="__mp_main__:app")
```

参考刚更新的 [MANUAL](https://github.com/nonebot/adapter-telegram/blob/beta/MANUAL.md#%E7%AC%AC%E4%B8%80%E6%AC%A1%E5%AF%B9%E8%AF%9D)

**Comment by MaGua-Bishop** [comment]
非常感谢您的回复，已成功解决问题并且echo成功
