### ISSUE TITLE
socks代理设置不成功

### ISSUE THREAD

**Issue by hellofinch** [nonebot/adapter-telegram#18]
按照文档说明安装了httpx[socks]包，并在.env中设置了`telegram_proxy=socks5://127.0.0.1:1080`。但是`nb run`之后无法执行`echo`操作。
利用privoxy将socks5协议转为http后，正常运行。
![image](https://user-images.githubusercontent.com/42131198/200545333-78939acd-e06b-4158-a218-ad439a70c38a.png)

**Comment by j1g5awi** [comment]
也許你安裝 httpx[socks] 包的 Python 環境不是你運行 NoneBot 的 Python 環境，我測試過安裝前 socks5 不可用，安裝後就行了。
