### ISSUE TITLE
bot.send 在 MessageEvent 为回复消息时报错 message thread not found

### ISSUE THREAD

**Issue by applenana** [nonebot/adapter-telegram#29]
![Screenshot_20230508_150109](https://user-images.githubusercontent.com/83851967/236769536-9e62ed7b-efe5-4fcc-a561-de7b9a4976fd.jpg)
↑这是出错的代码
当我修改成原生api来发送时，错误消失↓
![Screenshot_20230508_155837](https://user-images.githubusercontent.com/83851967/236769846-0838658d-c4ba-486e-8e67-1b3d207e2896.jpg)
奇怪的地方是，除了这个代码片段，别的matcher.send暂时没出现这个报错
不知道是不是bug

**Comment by applenana** [comment]
附带这个插件的代码
```python
from nonebot import on_command,on_message,on_keyword
from nonebot.adapters.telegram import api,bot,Message,MessageSegment
from nonebot.adapters.telegram.event import MessageEvent
from anyio import open_file
from nonebot.adapters.telegram import Bot
from nonebot.adapters.telegram.message import File
from nonebot.params import Arg, ArgPlainText, CommandArg, Matcher,EventMessage
from nonebot.permission import SUPERUSER
from nonebot.adapters.telegram.permission import *
from nonebot.message import run_postprocessor
from nonebot.typing import T_State
from nonebot_plugin_txt2img import Txt2Img
from nonebot.utils import *
import aiohttp
from PIL import Image, ImageFont, ImageDraw
import io
import wget
import time
import os
import requests
from dataclasses import replace
from operator import attrgetter
import time
from lib2to3.pgen2 import driver
from turtle import tilt
from unicodedata import name
from bs4 import BeautifulSoup
import json
import time
from playwright.async_api import async_playwright
from datetime import datetime
from nonebot import require,get_bot,get_driver
from nonebot_plugin_apscheduler import scheduler
require("nonebot_plugin_apscheduler")
from fake_useragent import UserAgent
from nonebot.rule import to_me


def img(text,title):
    # 标题设置为 '' 或 ' ' 可以去除标题行
    font_size = 32
    txt2img = Txt2Img()
    # 设置字体大小
    txt2img.set_font_size(font_size)

    # # 同时设置内容与标题字体大小
    # title_font_size = 48
    # txt2img.set_font_size(font_size, title_font_size)

    # # 设置固定宽度
    # # 设置后不会在内容较窄时自动调整宽度
    # width = 1080
    # txt2img.set_width(1080)

    # 绘制图片并发送
    pic = txt2img.draw(title, text)
    msg = MessageSegment.image(pic)
    return msg

async def replyRule(event:MessageEvent) ->bool:
    '''print(event)
    print(event.json())
    print(dir(event))'''
    return not event.reply_to_message is None

async def sendImg(bot,cid,bytes,more):
    iname=str(time.time())+'.jpg'
    with open(iname,'wb') as f:
        f.write(bytes)
    if more!='':
        mid=await bot.send_photo(chat_id=cid,photo=iname,caption=more)
    else:
        mid=await bot.send_photo(chat_id=cid,photo=iname)  
    os.remove(iname) 
    return mid

test=on_command('test')
@test.handle()
async def _(event:MessageEvent):
    await test.send(str(event.json()))
    print(1)
    await test.send('1')

history=on_command("历史上的今天")
@history.handle()
async def historytd():
    bot: Bot = get_bot()
    from datetime import datetime
    proxies = {
        "http": "socks5h://8.218.143.246:9980","https":"socks5h://8.218.143.246:9980"}
    headers={'accept-language':'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6'}
    async with aiohttp.ClientSession() as session:
        async with session.get("https://zh.wikipedia.org/wiki/Wikipedia:%E5%8E%86%E5%8F%B2%E4%B8%8A%E7%9A%84%E4%BB%8A%E5%A4%A9/"\
                               +str(datetime.now().month)+'月',headers=headers,proxy='http://127.0.0.1:10809') as resp:
            result=await resp.text()
        soup=BeautifulSoup(result,'lxml')
        #print(soup.find_all("div",attrs={"class":'mw-parser-output'}))
        nt=datetime.now()
        nt=str(nt.month)+'月'+str(nt.day)+'日'
        con='请求错误'+'\n'+'或者今天太普通啦🥱'

        i=soup.find('span',id=nt+'[编辑]').findParent('td')
        con=i.find("div",attrs={'class':'selected-anniversary'})
        festival=con.find('p').get_text()
        events=con.find_all('div',{'class':'event'})
        event=''
        pic=i.find('img').attrs['src'].replace('//',"")
        print('https://'+pic)
        async with session.get('https://'+pic,headers=headers,proxy='http://127.0.0.1:10809') as resp:
            pic=await resp.read()
    msglist=[festival,pic]
    text=''
    for m in range(len(events)):
        event+=events[m].get_text()
        if m < len(events)-1:
            text+=events[m].get_text().strip()+'\n'
            msglist.append(events[m].get_text().strip()+'\n')
        else:
            text+=events[m].get_text().strip()
            msglist.append(events[m].get_text().strip())
    #。.replace('\n','').replace('。','\n').replace('：','\n')
    imgname=str(time.time())+'.jpg'
    with open(imgname,'wb') as f:
        f.write(pic)    
        
    await bot.send_photo(chat_id=-1001939910021,photo=imgname,caption=festival+'\n'+text)
    os.remove(imgname)
''',
        InputMediaDocument(media=text)'''
scheduler.add_job(historytd, "cron",hour='6', minute=18, id="xxx")

htdapi=on_command('历史上的今天api')
@htdapi.handle()
async def htdapif():
    bot:Bot=get_bot()
    result=requests.get('https://v2.alapi.cn/api/eventHistory?token=oWRq2HhgZalHq9LH&month='+str(datetime.now().month)+'&day='+str(datetime.now().day)+'&page=1').text
    dic=eval(result)
    #print(dic)
    text='历史上的今天'+'\n'+str(datetime.now().month)+'月'+str(datetime.now().day)+'日：'
    for i in dic['data']:
        #time.sleep(1)
        text+='\n'+i['title']
        text+='\n'+i['desc']
        #text+='\n'+eval(requests.get('https://v2.alapi.cn/api/eventHistory/get?token=oWRq2HhgZalHq9LH&id='+str(i['id'])).text)['data']['content']
        text+='\n'+'---'+'\n'
    print(text)
    await bot.send_group_msg(group_id=int('864409825'), message='今日资讯:')
    await bot.send_group_msg(group_id=int('864409825'), message='历史上的今天')
    await bot.send_group_msg(group_id=int('864409825'), message=img(title='历史上的今天',text=text))

dailynews=on_command('每日日报')
@dailynews.handle()
async def dailynewsf():
    bot:Bot=get_bot()
    async with aiohttp.ClientSession() as session:
        async with session.get('https://v2.alapi.cn/api/zaobao?token=oWRq2HhgZalHq9LH&format=json') as resp:
            result=await resp.text()
        async with session.get(json.loads(result)['data']['image'].replace('\\','')) as resp:
            pic=await resp.read()

    await sendImg(bot=bot,cid=-1001939910021,bytes=pic,more='')

scheduler.add_job(dailynewsf, "cron",hour='6', minute=17, id="xx")

dailyweather=on_command('每日天气')
@dailyweather.handle()
async def dailyweatherf():
    bot:Bot=get_bot()
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page =await browser.new_page()
        await page.goto("http://products.weather.com.cn/yb.html?page=YB&type=YB_TQQS_3D")
        width = await page.evaluate("document.documentElement.scrollWidth")
        height =await page.evaluate("document.documentElement.scrollHeight")
        await page.set_viewport_size({'width':1080,'height':height})
        data=await page.locator('.tqgb').screenshot()
    await sendImg(bot,-1001939910021,data,'今日全国天气公报📢')
scheduler.add_job(dailyweatherf, "cron",hour='6', minute=16, id="weather")

epfree=on_command('喜加一')
@epfree.handle()
async def epfreef():
    bot:Bot=get_bot()
    if os.path.exists('epicfree'+str(datetime.now().month)+'月'+str(datetime.now().day)+'日'+'.jpg'):
        with open('epicfree'+str(datetime.now().month)+'月'+str(datetime.now().day)+'日'+'.jpg','rb') as f:
            data=f.read()
    else:
        async with async_playwright() as p:
            browser = await p.firefox.launch()
            page =await browser.new_page()
            width = await page.evaluate("document.documentElement.scrollWidth")
            height =await page.evaluate("document.documentElement.scrollHeight")
            await page.set_viewport_size({'width':1000,'height':1920})
            await page.goto("https://store.epicgames.com/zh-CN/free-games")
            await page.evaluate("Array.from(document.getElementsByClassName('css-1knv3fd')[0].children[1].children).forEach(function(element,index,array){console.log(index);console.log(element);if(index>3){console.log('Yes');element.remove();}})")
            await page.wait_for_load_state('networkidle')
            data=await page.locator('//*[@class="css-1knv3fd"]').screenshot()
        for i in os.listdir():
            if 'epic' in i and '.jpg' in i:
                os.remove(i)
        with open('epicfree'+str(datetime.now().month)+'月'+str(datetime.now().day)+'日'+'.jpg','wb') as f:
            f.write(data)
    await sendImg(bot,-1001939910021,data,'今日份喜加一！')
scheduler.add_job(epfreef, "cron",hour='6', minute=15, id="epicfree")   

global data
global today

today='data'
try:os.mkdir('EarthQuakeData')
except:pass
try:
    with open('EarthQuakeData/'+today+'.json') as f:
        data=json.load(f)
except:
    with open('EarthQuakeData/'+today+'.json','w') as f:
        f.write('{}')
        data={}
        data['eadd']={}
        data['eaq']=[]
earthquake=on_command('地震')
@earthquake.handle()
async def earthquakef():
    bot:Bot=get_bot()
    ua = UserAgent() 
    url='http://www.ceic.ac.cn/speedsearch'
    myheaders = {
        "User-Agent": ua.random
    }

    async with aiohttp.ClientSession() as session:
        async with session.get('http://www.ceic.ac.cn/speedsearch') as resp:
            result=await resp.text()
    soup=BeautifulSoup(result,'lxml')
    global data
    check=True
    for tr in soup.find('div',id='speed-search').find_all('tr'):
        try:
            tr.attrs['class'] == 'speed-tr-h1'
            continue
        except KeyError:pass
        if str(tr.find('a')) not in data['eaq']:
            ealist=tr.find_all('td')
            text=''
            text+='地震快报⚠️'+'\n'
            text+='在'+ealist[5].get_text()+'于'+ealist[1].get_text()+'发生'+ealist[0].get_text()+'级地震'+'\n'
            text+='维度:'+ealist[2].get_text()+'|经度:'+ealist[3].get_text()+'|震源'+ealist[4].get_text()+'km'
            mid=await bot.send_message(chat_id=-1001939910021, text=text)
            data['eadd'][mid.message_id]=tr.a.attrs['href']
            data['eaq'].append(str(tr.find('a')))
            print(data['eaq'])
            check=False
            with open('EarthQuakeData/'+today+'.json','w', encoding='utf-8') as f:
                json.dump(data,f,indent=4)
    if check:
        print(str(datetime.now())+'检查完毕，无新地震纪录')

global alarmData
if not os.path.exists('data'):
    os.mkdir('data')
if not os.path.exists('data/weatherAlarm.json'):
    with open('data/weatherAlarm.json','w',encoding='utf-8') as f:
        json.dump({'alarmData':{},'msgData':{},'subcity':[]},f)
with open('data/weatherAlarm.json','r',encoding='utf-8') as f:
    WWData=json.load(f)

weatherwarn=on_command('天气预警')
@weatherwarn.handle()
async def weatherwarnfunc():
    bot:Bot=get_bot()
    async with aiohttp.ClientSession() as session:
        async with session.get('http://product.weather.com.cn/alarm/grepalarm_cn.php') as resp:
            print(resp.status)
            #print(await resp.text())
            result= re.compile(u'{.*}').search(string=(await resp.text())).group()
    result=json.loads(result)
    if int(result['count']) <100:resultLen=int(result['count'])
    else:resultLen=100
    from .weatherAlarmConstant import kindObj
    from .weatherAlarmConstant import gradeObj
    for i in range(resultLen):
        datalist=result['data'][i]
        id=datalist[1]
        city=datalist[0]
        kind=kindObj[datalist[1].split('-')[2][0:2]]
        grade=gradeObj[datalist[1].split('-')[2][2:4]]
        timeall=datalist[1].split('-')[1]
        resultTime=timeall[:4]+'-'+timeall[4:6]+'-'+timeall[6:8]+' '+timeall[8:10]+':'+timeall[10:12]+':'+timeall[12:14]
        detail=[id,datalist[1].split('-')[2][0:4]]
        icon='http://www.weather.com.cn/m2/i/alarm_n/' + datalist[1].split('-')[2][0:4] + '.gif'
        if id not in WWData['alarmData']:
            WWData['alarmData'][id]={'city':city,'grade':grade,'kind':kind,'time':resultTime,'detail':detail,'icon':icon}
            subscribe=False
            for sc in WWData['subcity']:
                if sc in city:subscribe=True
            if subscribe:
                async with aiohttp.ClientSession() as session:
                    async with session.get(icon) as r:
                        pic=await r.read()
                mid=(await sendImg(bot,-1001939910021,pic,'[新的天气预警]'+'\n'+city+'发布'+grade+kind+'预警'+'\n'+resultTime)).message_id
                WWData['msgData'][str(mid)]=id
                print(str(mid))
            else:print('无新的预警')
    with open('data/weatherAlarm.json','w',encoding='utf-8') as f:
        json.dump(WWData,f)

subscribeCity=on_command('订阅预警')
@subscribeCity.handle()
async def _(msg:Message=CommandArg()):
    print(msg)
    global WWData
    WWData['subcity'].append(Message.extract_plain_text(msg))
    with open('data/weatherAlarm.json','w',encoding='utf-8') as f:
        json.dump(WWData,f)
    await subscribeCity.send('订阅成功')

DelSubscribeCity=on_command('删除预警订阅')
@DelSubscribeCity.handle()
async def _(msg:Message=CommandArg()):
    global WWData
    try:WWData['subcity'].remove(Message.extract_plain_text(msg))
    except:await DelSubscribeCity.send('删除失败，请检查是否订阅了此城市')
    else:
        with open('data/weatherAlarm.json','w',encoding='utf-8') as f:
            json.dump(WWData,f)
        await DelSubscribeCity.send('删除成功')

CheckSubCity=on_command('查看预警订阅')
@CheckSubCity.handle()
async def _():
    await CheckSubCity.send('订阅列表'+str(WWData['subcity']))

scheduler.add_job(earthquakef, "interval",seconds=60, id="earthquake")  
scheduler.add_job(weatherwarnfunc, "interval",seconds=60, id="weatherwarn")

everydetail=on_message(block=False,rule=replyRule)
@everydetail.handle()
async def _(t: T_State,bot:Bot, event: MessageEvent,msg:  Message = EventMessage(),):
    replyid=str(event.reply_to_message.message_id)
    print(replyid in WWData['msgData'])
    if replyid in data['eadd']:
        print(111111)
        await everydetail.send('详情:'+data['eadd'][replyid])
    if replyid in WWData['msgData']:
        print(222222)
        detail=WWData['alarmData'][WWData['msgData'][replyid]]['detail']
        id=detail[0]
        gk=detail[1]
        async with aiohttp.ClientSession() as session:
            async with session.get('http://product.weather.com.cn/alarm/webdata/'+id) as resp:
                result=json.loads(re.compile(u'{.*}').search(string=(await resp.text())).group())
                detailmsg=result['ISSUECONTENT']
            async with session.get('http://www.weather.com.cn/data/alarminfo/'+gk+'.html') as resp:
                result=(await resp.text()).split('","')
                #print(result)
                try:
                    name=result[1]
                    standard=result[2]
                    measure=result[3]
                except:
                    print('gk-'+gk)
                    name='请求失败'
                    standard=''
        print(detailmsg)
        await bot.send_message(int(event.chat.id),text=detailmsg)
        await bot.send_message(int(event.chat.id),text=name+'\n'+standard)
```

**Comment by j1g5awi** [comment]
请你提供更多出现该错误时的日志上下文，尤其该包含 matcher 所响应的消息，在 log_level=DEBUG 时可以看到。

**Comment by applenana** [comment]
> 请你提供更多出现该错误时的日志上下文，尤其该包含 matcher 所响应的消息，在 log_level=DEBUG 时可以看到。

`
05-08 20:03:27 [SUCCESS] nonebot | NoneBot is initializing...
05-08 20:03:27 [INFO] nonebot | Current Env: prod
05-08 20:03:27 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi+~httpx', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'123456789', '2806922724'}, 'nickname': {'awesome', 'bot'}, 'command_start': {'', '/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'telegram_bots': [{'token': '5902906872:AAFZsQZc1kN4jGbhoHegeVAErb5zECwjF2M'}], 'telegram_proxy': 'http://127.0.0.1:10809'}
05-08 20:03:28 [DEBUG] nonebot | Succeeded to load adapter "Telegram"
05-08 20:03:28 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
05-08 20:03:29 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
05-08 20:03:30 [DEBUG] nonebot | OneBot V12 | Model for key "" <class 'nonebot.adapters.onebot.v12.event.BotEvent'> is overridden by <class 'nonebot.adapters.onebot.v12.event.Event'>
05-08 20:03:32 [SUCCESS] nonebot | Succeeded to load plugin "everyday"
05-08 20:03:32 [SUCCESS] nonebot | Running NoneBot...
05-08 20:03:32 [DEBUG] nonebot | Loaded adapters: Telegram
05-08 20:03:33 [INFO] logging | Started server process [12220]
05-08 20:03:33 [INFO] logging | Waiting for application startup.
05-08 20:03:33 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-08 20:03:33 [INFO] logging | Application startup complete.
05-08 20:03:33 [INFO] logging | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
05-08 20:03:35 [INFO] nonebot | Telegram | Delete old webhook
05-08 20:03:37 [INFO] nonebot | Telegram | Start poll
05-08 20:03:49 [DEBUG] nonebot | Telegram | {'message_id': 135, 'date': 1683547427, 'chat': {'id': -1001939910021, 'type': 'supergroup', 'title': '苹果
香蕉泥🍋组'}, 'reply_to_message': {'message_id': 122, 'date': 1683533979, 'chat': {'id': -1001939910021, 'type': 'supergroup', 'title': '苹果香蕉泥🍋组'}, 'message': [新的天气预警]
黑龙江省双鸭山市友谊县发布蓝色大风预警
2023-05-08 16:15:00[photo:file=AgACAgUAAx0Ec6CthQADemRY5SQx8aaBr4VeQVt1tOfADSfLAAKLtDEbZ3fJVqZyyO9suyyUAQADAgADbQADLwQ], 'original_message': [新的天气预
警]
黑龙江省双鸭山市友谊县发布蓝色大风预警
2023-05-08 16:15:00[photo:file=AgACAgUAAx0Ec6CthQADemRY5SQx8aaBr4VeQVt1tOfADSfLAAKLtDEbZ3fJVqZyyO9suyyUAQADAgADbQADLwQ], 'from_': {'id': 5902906872, 'is_bot': True, 'first_name': '香蕉泥的bot', 'username': 'applenanabot'}}, 'message': hi, 'original_message': hi, 'from_': {'id': 5937847772, 'is_bot': False, 'first_name': 'Applenana', 'username': 'applnana', 'language_code': 'zh-hans'}, 'message_thread_id': 122}
05-08 20:03:49 [SUCCESS] nonebot | Telegram 5902906872 | [message.group.forum_topic]: Message 135 from 5937847772@[Chat -1001939910021 Thread 122]: hi
05-08 20:03:49 [DEBUG] nonebot | Checking for matchers in priority 1...
05-08 20:03:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=everyday)
05-08 20:03:49 [DEBUG] nonebot | Running Matcher(type='message', module=everyday)
05-08 20:03:49 [DEBUG] nonebot | Running handler Dependent(call=_)
True
222222
友谊县气象台2023年5月8日16时15分继续发布大风蓝色预警信号: 预计未来24小时，我县仍将受大风影响，平均风力5-6级，阵风7-8级，请有关单位及个人做好预防工作。（
预警信息来源：国家预警信息发布中心）
05-08 20:03:52 [INFO] nonebot | Matcher(type='message', module=everyday) running complete
05-08 20:03:52 [ERROR] nonebot | Running Matcher(type='message', module=everyday) failed.
Traceback (most recent call last):
  File "c:\Users\telegrame\Desktop\telegramebot\bot.py", line 15, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run      
    await handler(
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "c:\Users\telegrame\Desktop\telegramebot\everyday\__init__.py", line 324, in _
    await everydetail.send(detailmsg)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 466, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 133, in send
    return await self.send_message(
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 91, in call_api
    sign.return_annotation, await super().call_api(api, **kargs)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\telegram\adapter.py", line 213, in _call_api      
    raise ActionFailed(json.loads(response.content)["description"])
nonebot.adapters.telegram.exception.ActionFailed: <ActionFailed Bad Request: message thread not found>
05-08 20:03:52 [DEBUG] nonebot | Checking for matchers completed
`

**Comment by j1g5awi** [comment]
请你在 C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\telegram\adapter.py 的第 199 加入 `log("DEBUG", str(data))`，然后再复现一次 bug

**Comment by j1g5awi** [comment]
Event 判断有 bug，马上修复。

**Comment by j1g5awi** [comment]
c6e0d8be37b0ca3928d365e9434188d3cf625d38 fix it

**Comment by applenana** [comment]
使用最新的adapter/telegram的源码，仍然报错
05-08 23:47:22 [INFO] nonebot | Telegram | Delete old webhook
05-08 23:47:22 [DEBUG] nonebot | Telegram | {}
05-08 23:47:24 [INFO] nonebot | Telegram | Start poll
05-08 23:47:24 [DEBUG] nonebot | Telegram | {'timeout': '30'}
05-08 23:47:33 [DEBUG] nonebot | Telegram | {'offset': '88101599', 'timeout': '30'}
05-08 23:47:35 [DEBUG] nonebot | Telegram | {'message_id': 152, 'date': 1683560853, 'chat': {'id': -1001939910021, 'type': 'supergroup', 'title': '苹果
香蕉泥🍋组'}, 'reply_to_message': {'message_id': 120, 'date': 1683533916, 'chat': {'id': -1001939910021, 'type': 'supergroup', 'title': '苹果香蕉泥🍋组'}, 'message': [新的天气预警]
黑龙江省双鸭山市集贤县发布蓝色大风预警
2023-05-08 16:15:00[photo:file=AgACAgUAAx0Ec6CthQADeGRZGZXcMZVigySingoYmNHAki2SAAKLtDEbZ3fJVqZyyO9suyyUAQADAgADbQADLwQ], 'original_message': [新的天气预
警]
黑龙江省双鸭山市集贤县发布蓝色大风预警
2023-05-08 16:15:00[photo:file=AgACAgUAAx0Ec6CthQADeGRZGZXcMZVigySingoYmNHAki2SAAKLtDEbZ3fJVqZyyO9suyyUAQADAgADbQADLwQ], 'from_': {'id': 5902906872, 'is_bot': True, 'first_name': '香蕉泥的bot', 'username': 'applenanabot'}}, 'message': hi, 'original_message': hi, 'from_': {'id': 5937847772, 'is_bot': False, 'first_name': 'Applenana', 'username': 'applnana', 'language_code': 'zh-hans'}, 'message_thread_id': 120}
05-08 23:47:35 [SUCCESS] nonebot | Telegram 5902906872 | [message.group]: Message 152 from 5937847772@[Chat -1001939910021]: hi
05-08 23:47:35 [DEBUG] nonebot | Checking for matchers in priority 1...
05-08 23:47:35 [INFO] nonebot | Event will be handled by Matcher(type='message', module=everyday)
05-08 23:47:35 [DEBUG] nonebot | Running Matcher(type='message', module=everyday)
05-08 23:47:35 [DEBUG] nonebot | Running handler Dependent(call=_)
True
222222
05-08 23:47:35 [INFO] nonebot | Event will be handled by Matcher(type='message', module=aio)
05-08 23:47:35 [DEBUG] nonebot | Running Matcher(type='message', module=aio)
05-08 23:47:35 [DEBUG] nonebot | Running handler Dependent(call=_)
05-08 23:47:35 [DEBUG] nonebot | Telegram | {'chat_id': '-1001939910021', 'message_thread_id': '120', 'text': '', 'entities': '[]'}
集贤县气象台2023年5月8日16时15分继续发布大风蓝色预警信号：预计未来24小时，我县仍将受大风影响，平均风力5～6级，阵风7～8级，请有关单位及个人做好预防工作。
（预警信息来源：国家预警信息发布中心）
05-08 23:47:36 [DEBUG] nonebot | Telegram | {'chat_id': '-1001939910021', 'message_thread_id': '120', 'text': '集贤县气象台2023年5月8日16时15分继续发布 
大风蓝色预警信号：预计未来24小时，我县仍将受大风影响，平均风力5～6级，阵风7～8级，请有关单位及个人做好预防工作。（预警信息来源：国家预警信息发布中心）'}05-08 23:47:37 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_receive)),))
05-08 23:47:37 [INFO] nonebot | Matcher(type='message', module=aio) running complete
05-08 23:47:38 [INFO] nonebot | Matcher(type='message', module=everyday) running complete
05-08 23:47:38 [ERROR] nonebot | Running Matcher(type='message', module=everyday) failed.
Traceback (most recent call last):
  File "c:\Users\telegrame\Desktop\telegramebot\bot.py", line 16, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run      
    await handler(
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "c:\Users\telegrame\Desktop\telegramebot\everyday\__init__.py", line 324, in _
    await everydetail.send(detailmsg)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 466, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 133, in send
    return await self.send_message(
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\telegram\bot.py", line 91, in call_api
    sign.return_annotation, await super().call_api(api, **kargs)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\telegrame\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\adapters\telegram\adapter.py", line 214, in _call_api      
    raise ActionFailed(json.loads(response.content)["description"])
nonebot.adapters.telegram.exception.ActionFailed: <ActionFailed Bad Request: message thread not found>
05-08 23:47:38 [DEBUG] nonebot | Checking for matchers in priority 50...
05-08 23:47:38 [DEBUG] nonebot | Checking for matchers completed
05-08 23:47:38 [DEBUG] nonebot | Telegram | {'offset': '88101600', 'timeout': '30'}

**Comment by j1g5awi** [comment]
try 2e437f58b04b2819b002d6ac46b6deeb022eaaf4

**Comment by applenana** [comment]
bug已修复，谢谢大佬
