### ISSUE TITLE
如何发送带有@某个用户的消息

### ISSUE THREAD

**Issue by applenana** [nonebot/adapter-telegram#33]
如图这样的消息段
![Screenshot_20230509_164456](https://user-images.githubusercontent.com/83851967/237043893-7b610be4-bf98-417d-93c4-34dd73a84391.jpg)

**Comment by j1g5awi** [comment]
`Entity.text_miention` or `Entity.mention`

**Comment by applenana** [comment]
似乎有个小bug
### 在Message([Entity.mention(username)])这样的列表时，并不会mention
测试代码
user=event.telegram_model.message.from_
    username=event.telegram_model.message.from_.username
    await test.send(Entity.mention('@'+username))
    await test.send(Entity.text_mention('_(´□`」 ∠)_',user))
    await test.send(Message(['123','456',Entity.mention(username),Entity.text_mention('_(•̀ω•́ 」∠)_',user)]))

**Comment by applenana** [comment]
实际效果
![Screenshot_20230509_200917](https://github.com/nonebot/adapter-telegram/assets/83851967/10987f37-5de2-41c2-b2a1-5d18500b35a0)

**Comment by j1g5awi** [comment]
没有 @ 的话 Telegram 不会认为该 Entity 为 mention

**Comment by applenana** [comment]
> 没有 @ 的话 Telegram 不会认为该 Entity 为 mention

似乎并不是
我把代码修改为了    user=event.telegram_model.message.from_
    username=event.telegram_model.message.from_.username
    await test.send(Entity.mention('@'+username))
    await test.send(Entity.text_mention('_(´□`」 ∠)_',user))
    await test.send(Message(['123','456',Entity.mention('@'+username),Entity.text_mention('_(•̀ω•́ 」∠)_',user)]))

**Comment by applenana** [comment]
![Screenshot_20230509_222017](https://github.com/nonebot/adapter-telegram/assets/83851967/c51a5385-929f-4997-a177-23e8a37cc0a8)
效果还是如图

**Comment by applenana** [comment]
> 没有 @ 的话 Telegram 不会认为该 Entity 为 mention

而且我使用text_mention的时候。尽管text没有@也是可以产生mention链接的

**Comment by j1g5awi** [comment]
> 效果还是如图

那就是 mention 前需要空格，hashtag 同理

> 而且我使用text_mention的时候。尽管text没有@也是可以产生mention链接的

text_mention 和 mention 完全不是一个东西

---

mention 方法之后可以考虑自动加 `@` 前缀。

Entity 目前還有许多问題，比如 Telegram 支持多种样式叠加，如 **h~~el l~~o**，adapter-telegram 遇到会解析错误，之后可能要重写这部分逻辑。

**Comment by applenana** [comment]
> 

才看到这个，刚刚pr了一个现在可用的example

**Comment by applenana** [comment]
暂时没有更多问题，先close了
