### ISSUE TITLE
使用 aiohttp driver 会导致发送本地文件失败

### ISSUE THREAD

**Issue by Ailitonia** [nonebot/adapter-telegram#43]
## 环境
Windows 11 22H2
Python 3.10.11
nonebot2==2.0.0
nonebot-adapter-telegram==0.1.0b13

## 问题描述
使用示例发送本地图片
https://github.com/nonebot/adapter-telegram/blob/458326060ca3955de8b310e02c67f9d2c851c412/example/photo.py#L13-L20

代码如下：
```python
@on_command("photo2").handle()
async def _(bot: Bot, event: MessageEvent, matcher: Matcher):
    async with aiofiles.open(r"C:\Users\Ailit\Pictures\78868037_p0.png", "rb") as af:
        bytes_ = await af.read()

    try:
        await bot.send(event=event, message=File.photo(bytes_))
    except Exception as e:
        logger.error(f'bot send failed, {e}')

    try:
        await matcher.send(File.photo(bytes_))
    except Exception as e:
        logger.error(f'matcher send failed, {e}')
```

发送失败，提示 `ActionFailed Bad Request: there is no photo in the request`

![snipaste20230610_144931](https://github.com/nonebot/adapter-telegram/assets/41713304/844e01f0-2bad-43e3-bb90-71d4e20e35fc)

**Comment by j1g5awi** [comment]
无法复现错误，我甚至都在同个目录下创建文件了。

**Comment by j1g5awi** [comment]
~~麻烦你手动在 adapter.py 的第 203 行加入 `print(data)`，然后再运行一次。~~

你使用的 driver 是 aiohttp 吗？

**Comment by Ailitonia** [comment]
> ~麻烦你手动在 adapter.py 的第 203 行加入 `print(data)`，然后再运行一次。~
> 
> 你使用的 driver 是 aiohttp 吗？

证实, 该问题只会在 aiohttp driver 下发生, 改为 httpx 就正常了

**Comment by j1g5awi** [comment]
https://github.com/nonebot/nonebot2/pull/2088
