### ISSUE TITLE
如何让文字变得可复制

### ISSUE THREAD

**Issue by lingyunQAQ** [nonebot/adapter-telegram#46]
await bot.send(event, f'用户名：{user.username}\n'
                              f'UID：```{user.id}```\n'

貌似这样子并不可以（百度的）

**Comment by j1g5awi** [comment]
https://core.telegram.org/bots/api#markdownv2-style

在 Telegram 客户端中可复制的是 inline_code，你可以用 `Entity.code()` 发送或者直接用 `` ` `` 包裹该部分（同 markdown 语法）

**Comment by lingyunQAQ** [comment]
> Entity.code()

谢谢回复
我还是不理解
首先我使用bot.send 使用`包含`并不能让该字符串可复制

其次 Entity.code() 我没有找到在哪里导入，劳烦告诉我一下，谢谢

**Comment by lingyunQAQ** [comment]
> https://core.telegram.org/bots/api#markdownv2-style
> 
> 在 Telegram 客户端中可复制的是 inline_code，你可以用 `Entity.code()` 发送或者直接用 `` ` `` 包裹该部分（同 markdown 语法）

谢谢回复
我还是不理解
首先我使用bot.send 使用```包含并不能让该字符串可复制

其次 Entity.code() 我没有找到在哪里导入，劳烦告诉我一下，谢谢

**Comment by j1g5awi** [comment]
> https://core.telegram.org/bots/api#markdownv2-style To use this mode, pass MarkdownV2 in the parse_mode field. Use the following syntax in your message:

```python
bot.send("`it can be copied`", parse_mode="MarkdownV2")
```

---

```python
from nonebot.adapters.telegram.message import Entity
```

**Comment by lingyunQAQ** [comment]
> > https://core.telegram.org/bots/api#markdownv2-style To use this mode, pass MarkdownV2 in the parse_mode field. Use the following syntax in your message:
> 
> ```python
> bot.send("`it can be copied`", parse_mode="MarkdownV2")
> ```
> 
> ```python
> from nonebot.adapters.telegram.message import Entity
> ```

谢谢你的回复
我使用parse_mode="MarkdownV2"已解决问题
谢谢你的帮助

**Comment by lingyunQAQ** [comment]
> > https://core.telegram.org/bots/api#markdownv2-style To use this mode, pass MarkdownV2 in the parse_mode field. Use the following syntax in your message:
> 
> ```python
> bot.send("`it can be copied`", parse_mode="MarkdownV2")
> ```
> 
> ```python
> from nonebot.adapters.telegram.message import Entity
> ```

我想问一下怎么给指定UID用户发信息

**Comment by lingyunQAQ** [comment]
> > https://core.telegram.org/bots/api#markdownv2-style To use this mode, pass MarkdownV2 in the parse_mode field. Use the following syntax in your message:
> 
> ```python
> bot.send("`it can be copied`", parse_mode="MarkdownV2")
> ```
> 
> ```python
> from nonebot.adapters.telegram.message import Entity
> ```

我想做一个定时消息，用apscheduler，但是添加的时候总是无法把bot添加进去（因为要使用bot.send_message）
我该怎么做....第一次用这个开发，实在是不太理解其中的关系！

**Comment by j1g5awi** [comment]
#48 刚好来了个问这个的，你不犯他的错误就行。

**Comment by lingyunQAQ** [comment]
> #48 刚好来了个问这个的，你不犯他的错误就行。

OKOK
