### ISSUE TITLE
如何在 APScheduler 插件中正确获取到 Bot 对象并使用平台API

### ISSUE THREAD

**Issue by Umpire2018** [nonebot/adapter-telegram#48]
操作系统
Windows

Python 版本
3.11.3

NoneBot 版本
2.0.0

适配器
nonebot-adapter-telegram

在[nonebot 定时任务](https://nb2.baka.icu/docs/best-practice/scheduler)中提到，使用定时任务时需要调用[平台API](https://github.com/nonebot/adapter-telegram/blob/beta/nonebot/adapters/telegram/api.py)来发送消息，我当前的使用场景如下。

1. 首先通过 hook 在 driver 启动后仿照[nontbot 调用 API](https://nb2.baka.icu/docs/appendices/api-calling#%E8%B0%83%E7%94%A8-api) 获取到了Bot 对象 形如  `{'123456': Bot(type='Telegram', self_id='123456')}` 这是一个 dict 对象,我将其存储到 `config.py` 的 `Config` 类中
```python 
from nonebot import get_driver,get_bots
from .config import Config
driver = get_driver()

@driver.on_bot_connect
async def do_something():
    Conig.bots = get_bots()
```
2. 我定义了一个定时任务
```python
@scheduler.scheduled_job("cron", second='*/20', id="job_1")
async def send_message():
    await Conig.bots.call_api("send_message", chat_id='-123456',text='hi')
```

3. 在调用 `call_api` 时，我得到了 **`AttributeError: 'dict' object has no attribute 'call_api`**, 对象没有 `call_api` 属性

请问如何正确获取到 Bot 对象并使用平台API？

**Comment by j1g5awi** [comment]
> AttributeError: 'dict' object has no attribute 'call_api'

你使用 `get_bots` 得到的是 Dict[str, Bot]，有 `call_api` 方法的是 Bot 类。

**Comment by Umpire2018** [comment]
> > AttributeError: 'dict' object has no attribute 'call_api'
> 
> 你使用 `get_bots` 得到的是 Dict[str, Bot]，有 `call_api` 方法的是 Bot 类。

烦请不吝赐教，如何正确获取到 Bot 对象？

**Comment by lingyunQAQ** [comment]
> > > AttributeError: 'dict' object has no attribute 'call_api'
> > 
> > 
> > 你使用 `get_bots` 得到的是 Dict[str, Bot]，有 `call_api` 方法的是 Bot 类。
> 
> 烦请不吝赐教，如何正确获取到 Bot 对象？

get.bot好像就可以

**Comment by Umpire2018** [comment]
@lingyunQAQ 

```python 
Config.py
from nonebot.adapters.telegram import Bot
class Config():
    bot: Bot
```

```python 
scheduler.py
import nonebot
from nonebot import get_driver
from nonebot.adapters.telegram import Bot
from .config import Config
driver = get_driver()
@driver.on_bot_connect
async def do_something(bot: Bot):
   Config.bot =nonebot.get_bot()

@scheduler.scheduled_job("cron", second='*/20', id="job_1")
async def send_message():
    await Config.bot.call_api("send_message", chat_id='-123456',text='hi')
```

这的确是可行的，感谢。
