### ISSUE TITLE
接收不到群消息？

### ISSUE THREAD

**Issue by luochen1990** [nonebot/adapter-telegram#69]
我的bot能接收私聊bot的消息，但接收不到tg的群聊消息。

已确认一些细节:
1. 已经把bot拉进群了
2.  `message_listener = on_message()` 去掉了所有筛选条件。
3. 版本是 `nonebot-adapter-telegram@0.1.0b17` 和 `nonebot2@2.3.2`

**Comment by j1g5awi** [comment]
使用指南已寫明：

如果你需要让你的 Bot 响应除了 / 开头之外的消息，你需要向 BotFather 发送 /setprivacy 并选择 Disable。  
如果你需要让你的 Bot 接收 inline query，你还需要向 BotFather 发送 /setinline。

**Comment by luochen1990** [comment]
@j1g5awi 了解了，谢谢！

另外请教一下，怎么区分 `@my_bot` 的消息和没有 at 的消息？  我发现它们的消息体 （`message_fragment.__dict__`）是一样的

**Comment by luochen1990** [comment]
OK了，看起来用 `event.is_tome() == True` 可以区分:）  就是不知道大伙怎么 debug 的（指打印message）

**Comment by 2-3-5-7** [comment]
大家一定要把 `你需要向 BotFather 发送 /setprivacy 并选择 Disable。`  啊，这个选项根本不像描述里的那样（your bot will only receive messages that either start with the '/' symbol or mention the bot by username.），总之关了就对了
