### ISSUE TITLE
关于图片类型的消息序列默认获取的file_id问题

### ISSUE THREAD

**Issue by 5656565566** [nonebot/adapter-telegram#7]
接收图片时api返回原始数据中包含多个分辨率图片的file_id，而适配器返回的消息序列中使用的file_id是分辨率最低的一个，请问这是刻意为之还是其他的原因呢？

**Comment by j1g5awi** [comment]
因为如果是想将 Bot 接收到的图片再发送的话，使用哪个 `file_id` 的结果都是一样的。

当然，如果是为了下载图片，就要使用分辨率最高的 `file_id`。

我当时考虑过这个场景，但一直没人给我反馈，所以干脆就取第一个 `file_id` 了。

**Comment by 5656565566** [comment]
如果想获取发送到机器人的图片后续可能有计划提供一个方法吗？或者可以获取分辨率最高的 file_id 一直读原始数据还是挺麻烦的，还有目前构造图片消息序列可以使用 bytes 吗？

**Comment by j1g5awi** [comment]
消息段的 `file_id` 我可以换成分辨率最高的，下载图片的话还是得用 `get_file` API 获取文件链接下载，不会提供别的方法。

构造图片可以用 bytes，参考 <https://github.com/nonebot/adapter-telegram/blob/beta/example/photo.py>。
