### ISSUE TITLE
如何获取消息发送者的昵称？

### ISSUE THREAD

**Issue by luochen1990** [nonebot/adapter-telegram#70]
我尝试用以下代码打印信息

```python
@on_message().handle()
async def handle_message(bot: Bot, event: Event):
    print(f"{event.get_type() =}")
    print(f"{event.get_user_id() =}")
    ...
```

发现打印出来是这样

```
event.get_type() ='message'
event.get_user_id() ='131297xxxx'
event.get_event_name() ='message.group'
event.get_event_description() ='Message 50 from 131297xxxx@[Chat -4288xxxxx]: 你好'
event.get_log_string() ='[message.group]: Message 50 from 1312972489@[Chat -4288xxxxx]: 你好'
```

注意到这里 的 .get_user_id()  拿到的是像  '131297xxxx' 这样的 id，但是我没看到有类似 get_user_name() 之类的方法，请问要怎么获取到发送消息者的昵称？

**Comment by j1g5awi** [comment]
如果一条消息存在发送者，`event.from_` 即该用户。

User 类型存在 first_name、last_name、username 字段，一般來說 `f"{first_name} {last_name}"` 即 Telegram 客户端显示的用户名称，而 username 用于 at，需要注意的是在 telegram 中 last_name 和 username 都可能为 None。
